### ISSUE TITLE
ABHA Registration Functionality missing

### ISSUE THREAD

**Issue by senguptasudipta** [atul-gautam-au6/THIP-Issue-tracker#94] opened 2022-11-09 06:11 UTC
Create my ABHA ID should come as a checkbox in first registration (mobile number) input screen. [ Refer to #88 ]
OTP should go from ABHA for mobile verification is checkbox is checked
Next screen should have ABHA ID creation [<ID input field>@abdm]
Post that, registration flow should continue as it is.

[This is NOT full ABHA integration. This is just ABHA registration API]

**Comment by rohitrvayuz** [comment] 2022-11-10 04:48
@atul-gautam-au6  Please update here when done.

**Comment by rohitrvayuz** [comment] 2022-11-14 04:51
UI is done
@atul-gautam-au6  please share collection here

**Comment by rohitrvayuz** [comment] 2022-11-14 08:57
duplicate of #88

**Closed by rohitrvayuz** 2022-11-14 08:57 UTC
Labels: App
